import type { ShippingMethod } from "./types";

export const SHIPPING_METHODS: ShippingMethod[] = [
  {
    id: "mercari_nekopos",
    label: "らくらくメルカリ便 ネコポス",
    shippingFee: 210,
    maxLengthCm: 31.2,
    maxWidthCm: 22.8,
    maxHeightCm: 3,
    maxWeightG: 1000,
    availablePlatforms: ["mercari"],
    recommendedPackagingMaterialIds: ["envelope_padded", "box_nekopos"],
    note: "ポスト投函",
    sourceNote: "メルカリ便・主要比較用の概算マスタ",
  },
  {
    id: "mercari_yupacket",
    label: "ゆうゆうメルカリ便 ゆうパケット",
    shippingFee: 230,
    maxSumCm: 60,
    maxLengthCm: 34,
    maxWidthCm: 24,
    maxHeightCm: 3,
    maxWeightG: 1000,
    availablePlatforms: ["mercari"],
    recommendedPackagingMaterialIds: ["box_yupacket", "envelope_padded"],
    note: "ポスト投函",
    sourceNote: "メルカリ便・主要比較用の概算マスタ",
  },
  {
    id: "mercari_compact",
    label: "らくらくメルカリ便 宅急便コンパクト",
    shippingFee: 450,
    maxLengthCm: 25,
    maxWidthCm: 20,
    maxHeightCm: 5,
    maxWeightG: 2000,
    availablePlatforms: ["mercari"],
    recommendedPackagingMaterialIds: ["box_takkyubin_compact"],
    note: "対面受取（専用BOX想定）",
    sourceNote: "メルカリ便・主要比較用の概算マスタ",
  },
  {
    id: "mercari_yupacket_plus",
    label: "ゆうゆうメルカリ便 ゆうパケットプラス",
    shippingFee: 455,
    maxLengthCm: 24,
    maxWidthCm: 17,
    maxHeightCm: 7,
    maxWeightG: 2000,
    availablePlatforms: ["mercari"],
    recommendedPackagingMaterialIds: ["box_yupacket_plus"],
    note: "専用箱 / 対面または置き配",
    sourceNote: "メルカリ便・主要比較用の概算マスタ",
  },
  {
    id: "click_post",
    label: "クリックポスト",
    shippingFee: 185,
    maxLengthCm: 34,
    maxWidthCm: 25,
    maxHeightCm: 3,
    maxWeightG: 1000,
    recommendedPackagingMaterialIds: ["envelope_padded", "box_yupacket"],
    note: "ポスト投函",
    sourceNote: "日本郵便・主要比較用の概算マスタ",
  },
  {
    id: "letter_pack_light",
    label: "レターパックライト",
    shippingFee: 430,
    maxLengthCm: 34,
    maxWidthCm: 24.8,
    maxHeightCm: 3,
    maxWeightG: 4000,
    recommendedPackagingMaterialIds: ["none"],
    note: "専用封筒 / ポスト投函",
    sourceNote: "日本郵便・主要比較用の概算マスタ",
  },
  {
    id: "general_60",
    label: "一般宅配 60サイズ",
    shippingFee: 750,
    maxSumCm: 60,
    maxWeightG: 2000,
    recommendedPackagingMaterialIds: ["box_60_generic"],
    note: "対面配送",
    sourceNote: "主要宅配便の概算（比較用）",
  },
  {
    id: "general_80",
    label: "一般宅配 80サイズ",
    shippingFee: 850,
    maxSumCm: 80,
    maxWeightG: 5000,
    recommendedPackagingMaterialIds: ["box_80_generic"],
    note: "対面配送",
    sourceNote: "主要宅配便の概算（比較用）",
  },
  {
    id: "general_100",
    label: "一般宅配 100サイズ",
    shippingFee: 1050,
    maxSumCm: 100,
    maxWeightG: 10000,
    recommendedPackagingMaterialIds: ["box_100_generic"],
    note: "対面配送",
    sourceNote: "主要宅配便の概算（比較用）",
  },
  {
    id: "general_120",
    label: "一般宅配 120サイズ",
    shippingFee: 1200,
    maxSumCm: 120,
    maxWeightG: 15000,
    recommendedPackagingMaterialIds: ["box_120_generic"],
    note: "対面配送",
    sourceNote: "主要宅配便の概算（比較用）",
  },
  {
    id: "general_140",
    label: "一般宅配 140サイズ",
    shippingFee: 1450,
    maxSumCm: 140,
    maxWeightG: 20000,
    recommendedPackagingMaterialIds: ["box_140_generic"],
    note: "対面配送",
    sourceNote: "主要宅配便の概算（比較用）",
  },
  {
    id: "general_160",
    label: "一般宅配 160サイズ",
    shippingFee: 1700,
    maxSumCm: 160,
    maxWeightG: 25000,
    recommendedPackagingMaterialIds: ["box_160_generic"],
    note: "対面配送",
    sourceNote: "主要宅配便の概算（比較用）",
  },
];
